[application]

[web.app]

# HTML title tag content
title = "RTLauncher"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.RTLauncher"
publisher = "RTLauncher Development Team"

[tooling.tailwindcss]
file = "./input.css"
